name: Azure Python 3.5

on: [push]  # déclenche à chaque push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10.19
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.19

      - name: Install dependencies
        run: make install

      - name: Lint
        run: make lint

      - name: Test
        run: make test
